In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Vendor_Data.csv", index_col=False)

In [3]:
df

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume
0,Product 1,95,92,2.8,0.6,0.00323,0.08906
1,Product 2,37,27,10.0,0.8,0.00106,0.01991
2,Product 3,34,26,8.5,0.6,0.00328,0.03778
3,Product 4,32,30,2.8,0.7,0.00000,0.08562
4,Product 5,62,45,16.0,1.0,0.00079,0.02637
...,...,...,...,...,...,...,...
245,Product 246,23,21,2.0,1.5,0.00290,0.07129
246,Product 247,59,57,1.5,0.5,0.00000,0.05905
247,Product 248,16,15,0.9,1.6,0.00095,0.04835
248,Product 249,84,71,13.2,0.8,0.00264,0.00473
249,Product 250,38,28,9.7,2.1,0.00540,0.02149

In [4]:
profit = (df['Average_Profit_per_unit'] * df['Average_units_sold']).sum() * 0.05
profit

164.76350000000002

In [5]:
df['Acquisition'] = 5

In [6]:
df

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume,Acquisition
0,Product 1,95,92,2.8,0.6,0.00323,0.08906,5
1,Product 2,37,27,10.0,0.8,0.00106,0.01991,5
2,Product 3,34,26,8.5,0.6,0.00328,0.03778,5
3,Product 4,32,30,2.8,0.7,0.00000,0.08562,5
4,Product 5,62,45,16.0,1.0,0.00079,0.02637,5
...,...,...,...,...,...,...,...,...
245,Product 246,23,21,2.0,1.5,0.00290,0.07129,5
246,Product 247,59,57,1.5,0.5,0.00000,0.05905,5
247,Product 248,16,15,0.9,1.6,0.00095,0.04835,5
248,Product 249,84,71,13.2,0.8,0.00264,0.00473,5
249,Product 250,38,28,9.7,2.1,0.00540,0.02149,5

In [7]:
df_inc = df.copy()
df_dec = df.copy()

In [8]:
# What happens when we increase the price

def increase_price(df):
    df['Avg_Price_per_unit'] = df['Avg_Price_per_unit'] + (df['Avg_Price_per_unit'] * 1/100) # Incremement 1 percent on price
    df['Average_Profit_per_unit'] = df['Avg_Price_per_unit'] - df['Cost_per_unit']  # Profit Increases
    
    #df['Acquisition'] = df['Acquisition'] - (df['Incremental_acquisition'] / 10)
    df['Acquisition'] = df['Acquisition'] - (df['Incremental_acquisition'])  # Acquisition decreases
    df['Average_units_sold'] = df['Average_units_sold'] - (df['Increase_sale_volume'])  # Average Unit Sold Decreases

In [9]:
# What happens when we decrease the price

def decrease_price(df):
    df['Avg_Price_per_unit'] = df['Avg_Price_per_unit'] - (df['Avg_Price_per_unit'] * 1/100) # Decremement 1 percent
    df['Average_Profit_per_unit'] = df['Avg_Price_per_unit'] - df['Cost_per_unit']  # Profit Decreases
    
    #df['Acquisition'] = df['Acquisition'] + (df['Incremental_acquisition'] / 10)
    df['Acquisition'] = df['Acquisition'] + (df['Incremental_acquisition'])  # Acquisition increases
    df['Average_units_sold'] = df['Average_units_sold'] + (df['Increase_sale_volume'])  # Average Unit sold Increases

In [10]:
product_profit = pd.DataFrame() # DF with profit in 31 scenarios of all 250 products

In [11]:
product_profit[0] = df['Average_Profit_per_unit'] * df['Average_units_sold'] # Keeping in account of default product profit

In [12]:
# Increasing Price by 1% upto 20%
for i in range(20):
    increase_price(df_inc)
    profit_list = (df_inc['Average_Profit_per_unit'] * df_inc['Average_units_sold'])
    product_profit[i+2] = profit_list

In [13]:
# Decreasing Price by 1% upto 10%

for i in range(10):
    decrease_price(df_dec)
    profit_list = (df_dec['Average_Profit_per_unit'] * df_dec['Average_units_sold'])
    product_profit[-1 - i] = profit_list

In [14]:
product_profit

,0,2,3,4,5,6,7,8,9,10,...,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10
0,1.68,2.018213,2.071220,1.956514,1.671555,1.213769,0.580547,-0.230754,-1.222814,-2.398346,...,1.412573,0.863324,0.154709,-0.710849,-1.730960,-2.903265,-4.225438,-5.695184,-7.310239,-9.068368
1,8.00,8.089533,8.167146,8.232644,8.285832,8.326510,8.354476,8.369527,8.371454,8.360048,...,7.895733,7.779841,7.652511,7.513931,7.364285,7.203754,7.032516,6.850750,6.658627,6.456321
2,5.10,4.688915,4.553922,4.394654,4.210735,4.001788,3.767428,3.507266,3.220908,2.907954,...,4.885395,4.947396,4.986365,5.002658,4.996626,4.968616,4.918969,4.848024,4.756112,4.643563
3,1.96,1.425362,1.397618,1.315963,1.179576,0.987628,0.739279,0.433677,0.069957,-0.352754,...,1.319842,1.187674,1.004290,0.770468,0.486980,0.154585,-0.225967,-0.653936,-1.128594,-1.649220
4,16.00,17.155361,17.283895,17.385171,17.458748,17.504181,17.521019,17.508803,17.467070,17.395349,...,16.811941,16.597709,16.357730,16.092420,15.802191,15.487451,15.148598,14.786029,14.400132,13.991293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3.00,3.186023,3.342375,3.468594,3.564210,3.628748,3.661729,3.662662,3.631055,3.566406,...,2.781183,2.533351,2.256956,1.952444,1.620256,1.260826,0.874582,0.461946,0.023336,-0.440837
246,0.75,1.142061,1.216695,1.222878,1.159569,1.025714,0.820246,0.542081,0.190124,-0.236738,...,0.788260,0.510489,0.167690,-0.239144,-0.709035,-1.241017,-1.834139,-2.487460,-3.200055,-3.971009
247,1.44,1.799914,1.986761,2.160333,2.320418,2.466800,2.599264,2.717588,2.821548,2.910919,...,1.384614,1.156471,0.915774,0.662726,0.397525,0.120366,-0.168557,-0.469053,-0.780936,-1.104019
248,10.56,11.006537,11.611768,12.215640,12.818098,13.419089,14.018555,14.616440,15.212686,15.807233,...,9.785517,9.169887,8.553160,7.935388,7.316618,6.696899,6.076279,5.454803,4.832517,4.209466
249,20.37,21.574934,22.141352,22.699087,23.247968,23.787823,24.318477,24.839751,25.351466,25.853437,...,20.408734,19.809279,19.201797,18.586449,17.963393,17.332785,16.694777,16.049521,15.397164,14.737854

In [15]:
product_profit_t = product_profit.T

In [16]:
product_profit_t

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,1.680000,8.000000,5.100000,1.960000,16.000000,7.380000,53.390000,14.670000,29.700000,14.300000,...,23.760000,1.330000,42.340000,32.220000,24.300000,3.000000,0.750000,1.440000,10.560000,20.370000
2,2.018213,8.089533,4.688915,1.425362,17.155361,7.809293,53.589406,14.856617,29.547475,14.505150,...,26.023506,1.628081,41.404646,33.913035,25.598040,3.186023,1.142061,1.799914,11.006537,21.574934
3,2.071220,8.167146,4.553922,1.397618,17.283895,8.394031,53.881535,14.306718,30.266072,14.937938,...,28.049801,1.748279,42.115792,35.439825,26.174851,3.342375,1.216695,1.986761,11.611768,22.141352
4,1.956514,8.232644,4.394654,1.315963,17.385171,8.953807,54.074828,13.648667,30.955296,15.297224,...,30.078820,1.758954,42.731933,36.980499,26.730064,3.468594,1.222878,2.160333,12.215640,22.699087
5,1.671555,8.285832,4.210735,1.179576,17.458748,9.488209,54.167703,12.880808,31.614643,15.581853,...,32.110496,1.658443,43.251548,38.535189,27.263306,3.564210,1.159569,2.320418,12.818098,23.247968
6,1.213769,8.326510,4.001788,0.987628,17.504181,9.996819,54.158559,12.001459,32.243606,15.790654,...,34.144761,1.445060,43.673092,40.104026,27.774197,3.628748,1.025714,2.466800,13.419089,23.787823
7,0.580547,8.354476,3.767428,0.739279,17.521019,10.479211,54.045772,11.008920,32.841666,15.922440,...,36.181545,1.117098,43.994999,41.687145,28.262354,3.661729,0.820246,2.599264,14.018555,24.318477
8,-0.230754,8.369527,3.507266,0.433677,17.508803,10.934957,53.827696,9.901463,33.408301,15.976010,...,38.220778,0.672826,44.215682,43.284680,28.727386,3.662662,0.542081,2.717588,14.616440,24.839751
9,-1.222814,8.371454,3.220908,0.069957,17.467070,11.363618,53.502661,8.677340,33.942978,15.950142,...,40.262385,0.110490,44.333534,44.896768,29.168899,3.631055,0.190124,2.821548,15.212686,25.351466
10,-2.398346,8.360048,2.907954,-0.352754,17.395349,11.764755,53.068976,7.334780,34.445160,15.843603,...,42.306291,-0.571688,44.346922,46.523544,29.586490,3.566406,-0.236738,2.910919,15.807233,25.853437
11,-3.760103,8.335095,2.567999,-0.835343,17.293163,12.137917,52.524926,5.871986,34.914300,15.655138,...,44.352422,-1.375508,44.254193,48.165149,29.979754,3.468206,-0.739630,2.985470,16.400022,26.345480
12,-5.310871,8.296380,2.200633,-1.378709,17.160029,12.482650,51.868772,4.287139,35.349844,15.383480,...,46.400697,-2.302797,44.053673,49.821722,30.348279,3.335941,-1.319694,3.044968,16.990992,26.827406
13,-7.053476,8.243683,1.805439,-1.983763,16.995456,12.798494,51.098753,2.578394,35.751229,15.027340,...,48.451037,-3.355402,43.743663,51.493404,30.691645,3.169089,-1.978086,3.089179,17.580081,27.299023
14,-8.990779,8.176782,1.381996,-2.651426,16.798948,13.084982,50.213082,0.743882,36.117887,14.585416,...,50.503360,-4.535200,43.322439,53.180338,31.009429,2.967122,-2.715979,3.117861,18.167225,27.760137
15,-11.125681,8.095452,0.929877,-3.382634,16.570002,13.341638,49.209949,-1.218291,36.449240,14.056384,...,52.557582,-5.844087,42.788258,54.882668,31.301201,2.729503,-3.534560,3.130774,18.752360,28.210551
16,-13.461120,7.999466,0.448649,-4.178333,16.308106,13.567985,48.087519,-3.310045,36.744701,13.438906,...,54.613618,-7.283990,42.139350,56.600538,31.566525,2.455689,-4.435033,3.127671,19.335421,28.650066
17,-16.000075,7.888592,-0.062127,-5.039484,16.012744,13.763533,46.843931,-5.533324,37.003678,12.731624,...,56.671380,-8.856857,41.373922,58.334096,31.804959,2.145131,-5.418616,3.108304,19.916342,29.078477
18,-18.745564,7.762595,-0.602896,-5.967060,15.683391,13.927790,45.477301,-7.890099,37.225567,11.933161,...,58.730779,-10.564666,40.490157,60.083490,32.016054,1.797269,-6.486545,3.072419,20.495055,29.495580
19,-21.700643,7.621238,-1.174108,-6.962045,15.319515,14.060256,43.985717,-10.382367,37.409759,11.042124,...,60.791723,-12.409417,39.486211,61.848869,32.199356,1.411540,-7.640073,3.019761,21.071491,29.901165
20,-24.868410,7.464280,-1.776219,-8.025439,14.920578,14.160423,42.367243,-13.012152,37.555634,10.057098,...,62.854118,-14.393139,38.360218,63.630383,32.354403,0.987369,-8.880468,2.950071,21.645580,30.295022
21,-28.252005,7.291477,-2.409693,-9.158253,14.486032,14.227777,40.619916,-15.781505,37.662564,8.976653,...,64.917870,-16.517888,37.110285,65.428185,32.480728,0.524176,-10.209016,2.863085,22.217253,30.676933
-1,1.412573,7.895733,4.885395,1.319842,16.811941,6.558733,52.694527,15.630437,28.011635,13.412510,...,21.958106,1.060600,39.682966,30.885435,24.371040,2.781183,0.788260,1.384614,9.785517,20.408734
-2,0.863324,7.779841,4.947396,1.187674,16.597709,5.893550,52.094097,15.856617,27.195210,12.754305,...,19.919369,0.615545,38.674679,29.384655,23.721469,2.533351,0.510489,1.156471,9.169887,19.809279
-3,0.154709,7.652511,4.986365,1.004290,16.357730,5.204850,51.400235,15.980141,26.351207,12.026499,...,17.883848,0.066442,37.576608,27.897531,23.051647,2.256956,0.167690,0.915774,8.553160,19.201797
-4,-0.710849,7.513931,5.002658,0.770468,16.092420,4.493024,50.614443,16.002591,25.480103,11.230190,...,15.851600,-0.585124,36.390201,26.423932,22.361927,1.952444,-0.239144,0.662726,7.935388,18.586449
-5,-1.730960,7.364285,4.996626,0.486980,15.802191,3.758459,49.738205,15.925523,24.582367,10.366465,...,13.822683,-1.337587,35.116886,24.963731,21.652658,1.620256,-0.709035,0.397525,7.316618,17.963393
-6,-2.903265,7.203754,4.968616,0.154585,15.487451,3.001535,48.772983,15.750477,23.658462,9.436393,...,11.797152,-2.189405,33.758073,23.516802,20.924185,1.260826,-1.241017,0.120366,6.696899,17.332785
-7,-4.225438,7.032516,4.918969,-0.225967,15.148598,2.222629,47.720217,15.478969,22.708844,8.441028,...,9.775059,-3.139053,32.315151,22.083019,20.176846,0.874582,-1.834139,-0.168557,6.076279,16.694777
-8,-5.695184,6.850750,4.848024,-0.653936,14.786029,1.422110,46.581330,15.112495,21.733962,7.381411,...,7.756457,-4.185030,30.789490,20.662258,19.410976,0.461946,-2.487460,-0.469053,5.454803,16.049521
-9,-7.310239,6.658627,4.756112,-1.128594,14.400132,0.600344,45.357724,14.652532,20.734260,6.258568,...,5.741397,-5.325853,29.182442,19.254395,18.626904,0.023336,-3.200055,-0.780936,4.832517,15.397164
-10,-9.068368,6.456321,4.643563,-1.649220,13.991293,-0.242309,44.050781,14.100535,19.710174,5.073512,...,3.729929,-6.560061,27.495338,17.859310,17.824954,-0.440837,-3.971009,-1.104019,4.209466,14.737854

In [17]:
maxValueIndex = product_profit_t.idxmax()
maxValueIndex

0       3
1       9
2       0
3       0
4       7
       ..
245     8
246     4
247    15
248    21
249    21
Length: 250, dtype: int64

In [18]:
for i in range(len(df)):
    df.loc[i, "Avg_Price_per_unit"] = df.loc[i, "Avg_Price_per_unit"] + (df.loc[i, "Avg_Price_per_unit"] * (maxValueIndex[i]/100))
    df.loc[i, 'Average_Profit_per_unit'] = df.loc[i, 'Avg_Price_per_unit'] - df.loc[i, 'Cost_per_unit']
    
    df.loc[i, 'Acquisition'] = df.loc[i, 'Acquisition'] - (((maxValueIndex[i]/100)* df.loc[i, 'Incremental_acquisition']) / 10)
    df.loc[i, 'Average_units_sold'] = df.loc[i, 'Average_units_sold'] - (((maxValueIndex[i]/100)*df.loc[i, 'Increase_sale_volume']) / 10)
    
    print(df.loc[i, "Avg_Price_per_unit"])

97.85
40.33
34.0
32.0
66.34
104.06
110.25
80.64
83.49
116.64
82.32
127.05
31.04
59.29
82.28
24.2
114.45
67.76
88.2
16.66
56.87
117.37
33.95
123.12
53.11
55.0
110.11
73.71000000000001
44.69
39.93
90.75
100.8
24.2
26.62
43.24
53.5
45.9
42.0
35.1
22.2
103.68
15.120000000000001
128.7
42.0
55.66
113.4
56.87
93.1
92.22
55.66
69.35
72.9
119.48
44.769999999999996
47.7
42.12
133.1
50.4
13.31
77.44
25.3
16.94
107.06
111.1
68.2
94.05
56.87
116.62
85.02
54.45
98.7
104.06
54.06
23.0
84.6
50.6
63.6
71.0
40.74
85.8
68.97
16.56
94.38
62.92
25.41
66.55
29.04
94.34
87.74
112.2
61.2
86.0
79.86
78.0
39.9
80.84
78.3
63.28
74.12
75.24
42.78
100.58
133.1
56.43
88.33
41.14
125.84
116.16
16.94
62.72
109.89
79.86
74.52
61.11
66.55
68.9
20.0
106.7
22.31
61.75
41.3
92.16
81.62
123.42
30.78
99.64
17.0
32.86
66.55
50.82
64.96000000000001
37.06
93.17
105.27
48.4
28.8
39.93
75.6
70.18
48.4
75.84
131.89
44.769999999999996
56.16
100.43
34.3
111.18
96.8
71.54
33.64
58.24
105.27
107.69
43.86
67.76
30.25
89.25
48.51
49.22
107.69
83.49
96.04
70.29
71.39
35.1
91.96
24.2
44.769999999999996
101.2
14.0
14.0
29.0
50.0
31.0
81.6
87.72
55.93
96.8
82.62
106.82
98.0
36.05
125.84
56.64
41.0
78.21
23.0
19.8
88.11
78.75
48.02
29.7
49.5
57.04
24.3
29.9
70.8
49.0
41.34
101.92
73.78
44.85
46.44
114.33
23.1
16.94
84.7
30.25
41.14
58.5
37.51
55.08
98.94
40.95
99.36
99.22
31.92
119.78999999999999
103.95
85.91
120.64
33.6
53.94
54.45
18.15
20.52
39.93
25.52
65.55
49.0
12.1
50.88
88.2
89.53999999999999
100.43
56.16
44.03
16.240000000000002
61.88
120.91
107.69
67.6
75.9
102.85
121.0
24.84
61.36
18.4
101.64
45.98

In [19]:
df

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume,Acquisition
0,Product 1,97.85,92,5.85,0.599733,0.00323,0.08906,4.999990
1,Product 2,40.33,27,13.33,0.799821,0.00106,0.01991,4.999990
2,Product 3,34.00,26,8.00,0.600000,0.00328,0.03778,5.000000
3,Product 4,32.00,30,2.00,0.700000,0.00000,0.08562,5.000000
4,Product 5,66.34,45,21.34,0.999815,0.00079,0.02637,4.999994
...,...,...,...,...,...,...,...,...
245,Product 246,24.84,21,3.84,1.499430,0.00290,0.07129,4.999977
246,Product 247,61.36,57,4.36,0.499764,0.00000,0.05905,5.000000
247,Product 248,18.40,15,3.40,1.599275,0.00095,0.04835,4.999986
248,Product 249,101.64,71,30.64,0.799901,0.00264,0.00473,4.999945
249,Product 250,45.98,28,17.98,2.099549,0.00540,0.02149,4.999887

In [20]:
new_profit = (df['Average_Profit_per_unit'] * df['Average_units_sold']).sum() * 0.05
new_profit

308.89341562777